on:
  push:
    branches: [ main, master ]

name: Create new release

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ github.run_number }}
          release_name: Release ${{ github.ref }}-${{ github.run_number }}
          draft: false
          prerelease: false